--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 11 2024 20:56
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'WorkShift'   
-- start_time      :  
-- end_time        :  
--
CREATE TABLE WorkShift (
    start_time     TIMESTAMP NOT NULL,
    end_time       TIMESTAMP NOT NULL,
    CHECK(start_time < end_time),
CONSTRAINT pk_WorkShift PRIMARY KEY (start_time))
/


--
-- Create Table    : 'Person'   
-- F_Name          :  
-- L_Name          :  
-- City            :  
-- Address         :  
-- Id              :  
--
CREATE TABLE Person (
    F_Name         VARCHAR2(20) NOT NULL,
    L_Name         VARCHAR2(20) NOT NULL,
    City           VARCHAR2(30) NOT NULL,
    Address        VARCHAR2(30) NOT NULL,
    Id             NUMBER(38) NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY (Id))
/


--
-- Create Table    : 'Department'   
-- departId        :  
-- departName      :  
--
CREATE TABLE Department (
    departId       NUMBER(38) NOT NULL,
    departName     VARCHAR2(20) NOT NULL UNIQUE,
CONSTRAINT pk_Department PRIMARY KEY (departId))
/


--
-- Create Table    : 'Employee'   
-- Id              :  (references Person.Id)
-- joinDate        :  
-- salaryPerHour   :  
-- empRole         :  
-- departId        :  (references Department.departId)
--
CREATE TABLE Employee (
    Id             NUMBER(38) NOT NULL,
    joinDate       TIMESTAMP NOT NULL,
    salaryPerHour  NUMBER(10, 2) NOT NULL,
    empRole        VARCHAR2(20) NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_Employee PRIMARY KEY (Id),
CONSTRAINT fk_Employee2 FOREIGN KEY (Id)
    REFERENCES Person (Id),
CONSTRAINT fk_Employee FOREIGN KEY (departId)
    REFERENCES Department (departId)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'Set_on'   
-- Id              :  (references Employee.Id)
-- start_time      :  (references WorkShift.start_time)
--
CREATE TABLE Set_on (
    Id             NUMBER(38) NOT NULL,
    start_time     TIMESTAMP NOT NULL,
CONSTRAINT pk_Set_on PRIMARY KEY (Id,start_time),
CONSTRAINT fk_Set_on FOREIGN KEY (Id)
    REFERENCES Employee (Id)
    ON DELETE CASCADE,
CONSTRAINT fk_Set_on2 FOREIGN KEY (start_time)
    REFERENCES WorkShift (start_time))
/


--
-- Create Table    : 'Recruter'   
-- Id              :  (references Employee.Id)
--
CREATE TABLE Recruter (
    Id             NUMBER(38) NOT NULL,
CONSTRAINT pk_Recruter PRIMARY KEY (Id),
CONSTRAINT fk_Recruter FOREIGN KEY (Id)
    REFERENCES Employee (Id))
/


--
-- Create Table    : 'Manager'   
-- Id              :  (references Employee.Id)
-- departId        :  (references Department.departId)
--
CREATE TABLE Manager (
    Id             NUMBER(38) NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_Manager PRIMARY KEY (Id),
CONSTRAINT fk_Manager2 FOREIGN KEY (Id)
    REFERENCES Employee (Id),
CONSTRAINT fk_Manager FOREIGN KEY (departId)
    REFERENCES Department (departId))
/


--
-- Create Table    : 'FutureEmployee'   
-- Id1             :  (references Person.Id)
-- Id              :  (references Recruter.Id)
-- departId        :  (references Department.departId)
--
CREATE TABLE FutureEmployee (
    Id1            NUMBER(38) NOT NULL,
    Id             NUMBER(38) NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_FutureEmployee PRIMARY KEY (Id1),
CONSTRAINT fk_FutureEmployee3 FOREIGN KEY (Id1)
    REFERENCES Person (Id),
CONSTRAINT fk_FutureEmployee FOREIGN KEY (Id)
    REFERENCES Recruter (Id)
    ON DELETE CASCADE,
CONSTRAINT fk_FutureEmployee2 FOREIGN KEY (departId)
    REFERENCES Department (departId)
    ON DELETE CASCADE)
/


--
-- Permissions for: 'public'
--
GRANT ALL ON WorkShift TO public
/
GRANT ALL ON Person TO public
/
GRANT ALL ON Department TO public
/
GRANT ALL ON Employee TO public
/
GRANT ALL ON Set_on TO public
/
GRANT ALL ON Recruter TO public
/
GRANT ALL ON Manager TO public
/
GRANT ALL ON FutureEmployee TO public
/



