--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 10 2024 15:53
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Shfit'   
-- start_shift     :  
-- end_shift       :  
--
CREATE TABLE Shfit (
    start_shift    TIMESTAMP NOT NULL,
    end_shift      TIMESTAMP NOT NULL,
CONSTRAINT pk_Shfit PRIMARY KEY (start_shift))
/


--
-- Create Table    : 'Person'   
-- FirstName       :  
-- LastName        :  
-- City            :  
-- Address         :  
-- Id              :  
--
CREATE TABLE Person (
    FirstName      VARCHAR2(20) NOT NULL,
    LastName       VARCHAR2(20) NOT NULL,
    City           VARCHAR2(20) NOT NULL,
    Address        VARCHAR2(20) NOT NULL,
    Id             NUMBER(38) NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY (Id))
/


--
-- Create Table    : 'Department'   
-- departId        :  
-- departName      :  
--
CREATE TABLE Department (
    departId       NUMBER(38) NOT NULL,
    departName     VARCHAR2 NOT NULL UNIQUE,
CONSTRAINT pk_Department PRIMARY KEY (departId))
/


--
-- Create Table    : 'Employee'   
-- Id              :  (references Person.Id)
-- joinDate        :  
-- salaryPerHour   :  
-- empRole         :  
-- departId        :  (references Department.departId)
--
CREATE TABLE Employee (
    Id             NUMBER(38) NOT NULL,
    joinDate       TIMESTAMP NOT NULL,
    salaryPerHour  FLOAT NOT NULL,
    empRole        VARCHAR2 NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_Employee PRIMARY KEY (Id),
CONSTRAINT fk_Employee2 FOREIGN KEY (Id)
    REFERENCES Person (Id),
CONSTRAINT fk_Employee FOREIGN KEY (departId)
    REFERENCES Department (departId)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'Set_on_shift'   
-- Id              :  (references Employee.Id)
-- start_shift     :  (references Shfit.start_shift)
--
CREATE TABLE Set_on_shift (
    Id             NUMBER(38) NOT NULL,
    start_shift    TIMESTAMP NOT NULL,
CONSTRAINT pk_Set_on_shift PRIMARY KEY (Id,start_shift),
CONSTRAINT fk_Set_on_shift FOREIGN KEY (Id)
    REFERENCES Employee (Id)
    ON DELETE CASCADE,
CONSTRAINT fk_Set_on_shift2 FOREIGN KEY (start_shift)
    REFERENCES Shfit (start_shift))
/


--
-- Create Table    : 'Recruter'   
-- Id              :  (references Employee.Id)
--
CREATE TABLE Recruter (
    Id             NUMBER(38) NOT NULL,
CONSTRAINT pk_Recruter PRIMARY KEY (Id),
CONSTRAINT fk_Recruter FOREIGN KEY (Id)
    REFERENCES Employee (Id))
/


--
-- Create Table    : 'Manager'   
-- Id              :  (references Employee.Id)
-- departId        :  (references Department.departId)
--
CREATE TABLE Manager (
    Id             NUMBER(38) NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_Manager PRIMARY KEY (Id),
CONSTRAINT fk_Manager2 FOREIGN KEY (Id)
    REFERENCES Employee (Id),
CONSTRAINT fk_Manager FOREIGN KEY (departId)
    REFERENCES Department (departId))
/


--
-- Create Table    : 'FutureEmployee'   
-- Id1             :  (references Person.Id)
-- Id              :  (references Recruter.Id)
-- departId        :  (references Department.departId)
--
CREATE TABLE FutureEmployee (
    Id1            NUMBER(38) NOT NULL,
    Id             NUMBER(38) NOT NULL,
    departId       NUMBER(38) NOT NULL,
CONSTRAINT pk_FutureEmployee PRIMARY KEY (Id1),
CONSTRAINT fk_FutureEmployee3 FOREIGN KEY (Id1)
    REFERENCES Person (Id),
CONSTRAINT fk_FutureEmployee FOREIGN KEY (Id)
    REFERENCES Recruter (Id)
    ON DELETE CASCADE,
CONSTRAINT fk_FutureEmployee2 FOREIGN KEY (departId)
    REFERENCES Department (departId)
    ON DELETE CASCADE)
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Shfit TO public
/
GRANT ALL ON Person TO public
/
GRANT ALL ON Department TO public
/
GRANT ALL ON Employee TO public
/
GRANT ALL ON Set_on_shift TO public
/
GRANT ALL ON Recruter TO public
/
GRANT ALL ON Manager TO public
/
GRANT ALL ON FutureEmployee TO public
/

exit;

