Drop Table EmployeeTraining;
Drop Table Manager;
Drop Table LeaveRequest;
Drop Table EmployeeShift;
Drop Table Shift;
Drop Table Training;
Drop Table Employee;
Drop Table Position;
Drop Table Department;
